site_name: 生产环境集群实战
theme: readthedocs
pages:
- Homepage: index.md
#- base:
#  - dis: base-tech.md
#  - docker: base-docker.md
#  - vagrant: base-vagrant.md
- 部署k8s集群:
  - 跳板机: k8s-proxy.md
  - 构建基础镜像: k8s-install.md
  - 部署单点集群: k8s-cluster.md
  - 部署高可用集群: k8s-ha.md
  - web开发实战: k8s-web.md
- 部署RabbitMQ集群: rabbitmq.md
- 部署Redis集群: redis.md