site_name: 生产环境集群实战
theme: readthedocs
nav:
- Homepage: index.md
#- base:
#  - dis: base-tech.md
#  - docker: base-docker.md
#  - vagrant: base-vagrant.md
- k8s:
  - bridge: k8s-proxy.md
  - base: k8s-install.md
  - sig: k8s-cluster.md
  - ha: k8s-ha.md
  - web: k8s-web.md
- rabbitMQ: rabbitmq.md
- redis: redis.md